FROM elixir:1.17.2-otp-27

ENV NODE_VERSION=22.7.0

# Install debian packages
RUN apt-get update && \
    apt-get install --yes build-essential inotify-tools postgresql-client git && \
    apt-get clean

ADD . /app

# Install Phoenix packages
RUN mix local.hex --force && \
    mix local.rebar --force

# install nodejs
RUN curl -L -o node.tar.xz "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" && \
  tar -xJf node.tar.xz -C /usr/local --strip-components=1 && \
  rm node.tar.xz && \
  ln -s /usr/local/bin/node /usr/local/bin/nodejs


WORKDIR /app

RUN mix deps.get
RUN npm install --prefix client

EXPOSE 4000

CMD ["/app/entrypoint.sh"]
