version: '3.9'
volumes:
  postgres-kaibosh:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=kaibosh
      - POSTGRES_PASSWORD=kaibosh
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=kaibosh
      - POSTGRES_PASSWORD=kaibosh
    volumes:
      - postgres-kaibosh:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
