version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - dev.env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kaibosh
      - POSTGRES_PASSWORD=kaibosh
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
