FROM elixir:1.15.0

# Install debian packages
RUN apt-get update && \
    apt-get install --yes build-essential inotify-tools postgresql-client git && \
    apt-get clean

ADD . /app

# Install Phoenix packages
RUN mix local.hex --force && \
    mix local.rebar --force

# Install node
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs

WORKDIR /app

RUN mix deps.get
RUN npm install --prefix ./assets

EXPOSE 4000

CMD ["/app/entrypoint.sh"]
